# Generated by Django 2.1.7 on 2019-03-24 17:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_group_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=128, null=True)),
                ('screen_name', models.CharField(max_length=20, null=True)),
                ('is_closed', models.PositiveIntegerField(null=True)),
                ('deactivated', models.CharField(max_length=8, null=True)),
                ('is_admin', models.BooleanField(null=True)),
                ('admin_level', models.PositiveIntegerField(null=True)),
                ('is_member', models.BooleanField(null=True)),
                ('invited_by', models.PositiveIntegerField(null=True)),
                ('type', models.CharField(max_length=5, null=True)),
                ('activity', models.CharField(max_length=128, null=True)),
                ('age_limits', models.PositiveIntegerField(null=True)),
                ('ban_info', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('can_create_topic', models.BooleanField(null=True)),
                ('can_message', models.BooleanField(null=True)),
                ('can_post', models.BooleanField(null=True)),
                ('can_see_all_posts', models.BooleanField(null=True)),
                ('can_upload_doc', models.BooleanField(null=True)),
                ('can_upload_video', models.BooleanField(null=True)),
                ('city', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('contacts', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('counters', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('country', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('cover', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('description', models.CharField(max_length=128, null=True)),
                ('fixed_post', models.PositiveIntegerField(null=True)),
                ('has_photo', models.BooleanField(null=True)),
                ('is_favorite', models.BooleanField(null=True)),
                ('is_hidden_from_feed', models.BooleanField(null=True)),
                ('is_messages_blocked', models.BooleanField(null=True)),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('main_album_id', models.PositiveIntegerField(null=True)),
                ('main_section', models.PositiveIntegerField(null=True)),
                ('market', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('member_status', models.PositiveIntegerField(null=True)),
                ('members_count', models.PositiveIntegerField(null=True)),
                ('place', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('public_date_label', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('site', models.CharField(max_length=64, null=True)),
                ('start_date', models.CharField(max_length=10, null=True)),
                ('finish_date', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(max_length=64, null=True)),
                ('trending', models.BooleanField(null=True)),
                ('verified', models.BooleanField(null=True)),
                ('wall', models.PositiveIntegerField(null=True)),
                ('wiki_page', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VkWalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_id', models.PositiveIntegerField(null=True)),
                ('record_id', models.PositiveIntegerField(null=True)),
                ('owner_id', models.PositiveIntegerField(null=True)),
                ('from_id', models.PositiveIntegerField(null=True)),
                ('date', models.PositiveIntegerField(null=True)),
                ('text', models.TextField(null=True)),
                ('reply_owner_id', models.PositiveIntegerField(null=True)),
                ('reply_post_id', models.PositiveIntegerField(null=True)),
                ('comments', models.PositiveIntegerField(null=True)),
                ('likes', models.PositiveIntegerField(null=True)),
                ('reposts', models.PositiveIntegerField(null=True)),
                ('views', models.PositiveIntegerField(null=True)),
                ('post_type', models.CharField(max_length=40, null=True)),
                ('attachments', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('geo', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('signer_id', models.PositiveIntegerField(null=True)),
                ('copy_history', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('can_pin', models.BooleanField(null=True)),
                ('can_delete', models.BooleanField(null=True)),
                ('can_edit', models.BooleanField(null=True)),
                ('is_pinned', models.BooleanField(null=True)),
                ('marked_as_ads', models.BooleanField(null=True)),
                ('is_favorite', models.BooleanField(null=True)),
                ('vk_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.VkGroups')),
            ],
        ),
    ]
