# Generated by Django 2.1.4 on 2019-03-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupVkProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_id', models.IntegerField(default=0, verbose_name='id группы vk')),
                ('posts_likes', models.PositiveIntegerField(default=0, verbose_name='Количество лайков поста')),
                ('posts_text', models.TextField(blank=True, verbose_name='Текст поста группы vk')),
                ('posts_date', models.CharField(blank=True, max_length=64, verbose_name='Дата поста ')),
                ('posts_comments', models.PositiveIntegerField(default=0, verbose_name='Количество комментов поста')),
                ('posts_reposts', models.PositiveIntegerField(default=0, verbose_name='Количество репостов поста')),
            ],
        ),
    ]
