# Generated by Django 2.1.4 on 2019-03-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupVkProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(default=0, verbose_name='id группы vk')),
                ('post_likes', models.PositiveIntegerField(default=0, verbose_name='Количество лайков поста')),
                ('post_text', models.TextField(blank=True, verbose_name='Текст поста группы vk')),
                ('post_dates', models.DateTimeField(verbose_name='Дата поста ')),
                ('post_comments', models.PositiveIntegerField(default=0, verbose_name='Количество комментов поста')),
                ('post_reposts', models.PositiveIntegerField(default=0, verbose_name='Количество репостов поста')),
            ],
        ),
    ]
