# Generated by Django 2.1.4 on 2019-03-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataqueryapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupVkProfile',
        ),
    ]
