# Generated by Django 2.1.4 on 2019-03-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataqueryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupvkprofile',
            old_name='post_dates',
            new_name='post_date',
        ),
    ]
