# Generated by Django 2.1.4 on 2019-03-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataqueryapp', '0002_auto_20190316_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupvkprofile',
            old_name='post_comments',
            new_name='posts_comments',
        ),
        migrations.RenameField(
            model_name='groupvkprofile',
            old_name='post_date',
            new_name='posts_date',
        ),
        migrations.RenameField(
            model_name='groupvkprofile',
            old_name='post_id',
            new_name='posts_id',
        ),
        migrations.RenameField(
            model_name='groupvkprofile',
            old_name='post_likes',
            new_name='posts_likes',
        ),
        migrations.RenameField(
            model_name='groupvkprofile',
            old_name='post_reposts',
            new_name='posts_reposts',
        ),
        migrations.RenameField(
            model_name='groupvkprofile',
            old_name='post_text',
            new_name='posts_text',
        ),
    ]
