# Generated by Django 2.1.4 on 2019-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataqueryapp', '0003_auto_20190317_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupvkprofile',
            name='posts_date',
            field=models.DateField(blank=True, verbose_name='Дата поста '),
        ),
    ]
