# Generated by Django 2.1.4 on 2019-03-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataqueryapp', '0004_auto_20190317_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupvkprofile',
            name='posts_date',
            field=models.CharField(blank=True, max_length=64, verbose_name='Дата поста '),
        ),
    ]
